apiVersion: v1
entries:
  gateway:
  - apiVersion: v2
    appVersion: 1.12.0
    created: "2022-01-07T08:46:12.737322+01:00"
    description: Helm chart for deploying Istio gateways
    digest: 1ebc770b2bdc92a59e602c3b957211a91a4e587f5d393e247abba747ada99931
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - gateways
    name: gateway
    sources:
    - http://github.com/istio/istio
    type: application
    urls:
    - gateway-1.12.0.tgz
    version: 1.12.0
generated: "2022-01-07T08:46:12.735436+01:00"
